### ISSUE TITLE
Problem after upgrade HA Core to 2024.1.0b0

### ISSUE THREAD

**Issue by marlonqpa** [sehaas/ha_hisense_tv#57]
Hi 

After upgrading HA Core to 2024.0.b0 I've got this error on this integration loading:

```
Error while setting up hisense_tv platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1080, in capability_attributes
    ) and MediaPlayerEntityFeature.SELECT_SOURCE in supported_features:
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable
```

**Comment by marlonqpa** [comment]
I think it could be related to this:
[https://developers.home-assistant.io/blog/2022/04/02/support-constants-deprecation/](url)
